// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmq82wKVFLZLdAOGTmZK4iFJZpgFqVRxY',
    appId: '1:498730641513:web:591ca8c865d519f9a09af8',
    messagingSenderId: '498730641513',
    projectId: 'easytodo-a2ddb',
    authDomain: 'easytodo-a2ddb.firebaseapp.com',
    storageBucket: 'easytodo-a2ddb.firebasestorage.app',
    measurementId: 'G-VHF7FWQ94B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5LMBxXdendR-sC-gpFLVRGItshYFbBI',
    appId: '1:498730641513:android:15eb2d6a5fecd88aa09af8',
    messagingSenderId: '498730641513',
    projectId: 'easytodo-a2ddb',
    storageBucket: 'easytodo-a2ddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnBNfVAO8u92qrQ0P5CZBjtnNnFVL6ho',
    appId: '1:498730641513:ios:2fdfeabe3d342038a09af8',
    messagingSenderId: '498730641513',
    projectId: 'easytodo-a2ddb',
    storageBucket: 'easytodo-a2ddb.firebasestorage.app',
    iosClientId:
        '498730641513-3nrn9q6ndu5iuuqjlvr0upu576thn1qg.apps.googleusercontent.com',
    iosBundleId: 'com.ramonito.easyTodo',
  );
}
